{
	[
		'../src/*',
		'../src/lib/*',
		'../src/lib/mysql/*',
		'../src/mod/*',
		'../src/pp/*',
		'../src/proto/*',
                '../src/data/*',
		'../src/test/*',
		'../src/test/performance/*',
		'../src/test/script/*'
	]
	,[
		debug_info
		,{i, "../include"}
		,{outdir, "../ebin"}
	]
}.
